waypoints:
    - point:
        x: -0.00617719
        y: 4.06657
        z: 0
        function: run
    - point:
        x: 0.480574
        y: 28.9264
        z: 1.90735e-06
        function: suspend
    - point:
        x: -9.55865
        y: 29.2967
        z: 1.90735e-06
        function: run
    - point:
        x: -10.6357
        y: -4.68372
        z: 0
        function: run
    - point:
        x: -0.521227
        y: -4.52424
        z: -1.90735e-06
        function: suspend
    - point:
        x: 5.23454
        y: -0.497696
        z: -1.90735e-06
        function: run
    - point:
        x: 13.9648
        y: -0.548787
        z: -1.90735e-06
        function: run
    - point:
        x: 40.6828
        y: -0.386804
        z: 1.90735e-06
        function: suspend
    - point:
        x: 14.0587
        y: -1.06467
        z: -5.72205e-06
        function: run
    - point:
        x: 14.9574
        y: 26.9753
        z: 1.90735e-06
        function: run
    - point:
        x: 40.6517
        y: 27.8239
        z: 5.72205e-06
        function: suspend
    - point:
        x: 14.7763
        y: 27.6431
        z: 1.90735e-06
        function: run
    - point:
        x: 14.886
        y: -0.385885
        z: 1.90735e-06
        function: run
    - point:
        x: 0.557234
        y: -0.413141
        z: 0
        function: run
