# move_base common parameters

DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.2
  min_vel_x: 0

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans: 0.9
  min_vel_trans: 0.1
  
  max_vel_theta: 1.5
  min_vel_theta: 0.8

  acc_lim_x: 10.0
  acc_lim_y: 0.0
  acc_lim_theta: 10.0

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 2
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 20
  vy_samples: 0
  vth_samples: 30

# Trajectory Scoring Parameters
  path_distance_bias: 0.4
  goal_distance_bias: 0.6
  occdist_scale: 0.0004
  twirling_scale: 0.0
  forward_point_distance: 0.3
  stop_time_buffer: 0.2
  scaling_speed: 1.0
